batch_size: 16
data_path: "/hz/data/pointcloud/train/"
model: 'pointMLP_medium_sampling'
sample_groups: 4096
learning_rate: 0.01
epoch: 600
log_interval: 30
model_name: "20240415_embed64_knb24"
loss_weights_list: [0.2, 0.8]
use_L1: true
step_size: 150