batch_size: 16
data_path: "/content/pointmlp/data/pointcloud/train"
model: 'pointMLP_small_sampling'
sample_groups: 4096
learning_rate: 0.02
epoch: 600
log_interval: 30
model_name: "20240415_sharedweights"
loss_weights_list: [0.2, 0.8]
use_L1: true
step_size: 150
log_path: "/content/drive/MyDrive/pointmlp/checkpoints"