batch_size: 16
data_path: "/kaggle/input/pc-tooth/pointcloud/train"
log_path: "/kaggle/working/checkpoints"
model: 'pointMLP_sampling'
sample_groups: 4096
learning_rate: 0.0005
epoch: 600
log_interval: 20
model_name: "kaggle_0.005"
loss_weights_list: [0.2, 0.8]
use_L1: true