batch_size: 16
data_path: "/hz/data/pointcloud/train/"
#model: 'pointMLP_hz'
#model: 'pointMLPElite_hz'
#model: 'pointMLP_elite_sampling'
model: 'pointMLP_sampling'
sample_groups: 4096
learning_rate: 0.01
epoch: 600
log_interval: 60
#model_name: "20240409_catpoints_1"
model_name: "20240414_tanh_0.01"
loss_weights_list: [0.2, 0.8]