batch_size: 8
data_path: "/hz/data/pointcloud/train/"
#model: 'pointMLP_hz'
model: 'pointMLPElite_hz'
sample_groups: 4096
learning_rate: 0.05
epoch: 600
log_interval: 60
#model_name: "20240409_catpoints_1"
model_name: "20240410_catpoints_avgpool"